version: '3.8'

services:
  MariaDB:
    container_name: MariaDB
    image: ${DB_IMAGE}
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - MariaDB:/var/lib/mysql
    networks:
      - Frappe

  frappe-bench:
    container_name: frappe-bench
    image: ${IMAGE_NAME}
    restart: unless-stopped
    volumes:
      - Frappe-Sites:/home/ubuntu/frappe-bench/sites
      - Frappe-Apps:/home/ubuntu/frappe-bench/apps
    networks:
      - Frappe
    ports:
      - 8000:8000
  
  configurator:
    container_name: configurator
    image: ${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench set-config -g db_host ${DB_HOST};
        bench set-config -g db_port "${DB_PORT}";
        bench set-config -g redis_cache "redis://${REDIS_CACHE}";
        bench set-config -g redis_queue "redis://${REDIS_QUEUE}";
        bench set-config -g redis_socketio "redis://${REDIS_SOCKETIO}";
        bench set-config -g socketio_port "${SOCKETIO_PORT}";
    volumes:
      - Frappe-Sites:/home/ubuntu/frappe-bench/sites
      - Frappe-Apps:/home/ubuntu/frappe-bench/apps
    networks:
      - frappe

volumes:
  MariaDB:
    name: MariaDB
  Frappe-Sites:
    name: Frappe-Sites
  Frappe-Apps:
    name: Frappe-Apps

networks:
  Frappe:
    name: Frappe
